apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dapr-microservices-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        awsLoadBalancerController: true
        cloudWatch: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver

cloudWatch:
  clusterLogging:
    enable: ["api", "audit", "authenticator", "controllerManager", "scheduler"]